# ==================================================================================================
# --- Structure of the study ---
# ==================================================================================================
name: trees/BBCW_SCAN_2025

# List all useful files that will be used by executable in generations below
# These files are placed at the root of the study
dependencies:
  main_configuration: configs/config_1_base.yaml
  # Custom dependencies
  submodules : 
    - scripts/xsuiteplus.py
    - scripts/compute_residual.py
    - configs/config_2_nlr.yaml
    - configs/config_3_nlr.yaml
    - fillingschemes/2025_config_5x36_converted.json


structure:
  # First generation is always at the root of the study
  # such that config_runIII.yaml is accessible as ../config_runIII.yaml
  generation_1:
    executable: scripts/generation_1.py
    scans:
    common_parameters:
      # Needs to be redeclared as it's used for parallelization
      # And re-used ine the second generation
      n_split: 5

  # Second generation depends on the config from the first generation
  generation_2:
    executable: scripts/generation_2_nb_leveling.py
    scans:
      distribution_file:
        # Number of paths is set by n_split in the main config
        path_list: ["____.parquet", n_split]

      # BBCW current scan
      i_bbcw_4l1_b1:
        linspace: [0,300, 2]
      i_bbcw_4l5_b1:
        linspace: [0,300, 2]


      # Linking Beam 2 to Beam 1 (concomitant)
      i_bbcw_4r1_b2:
        expression: i_bbcw_4l1_b1
        concomitant: [i_bbcw_4l1_b1]
      i_bbcw_4r5_b2:
        expression: i_bbcw_4l5_b1
        concomitant: [i_bbcw_4l5_b1]
